name: Examples

on:
  pull_request:
    branches: [main]

env:
  PACKAGE_NAME: MistKit

jobs:
  test-examples:
    name: Test ${{ matrix.example }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    strategy:
      fail-fast: false
      matrix:
        example: [MistDemo, BushelCloud, CelestraCloud]
        swift:
          - version: "6.2"
        include:
          - example: MistDemo
            os: ubuntu-latest
          - example: MistDemo
            os: macos-latest
          - example: BushelCloud
            os: ubuntu-latest
          - example: BushelCloud
            os: macos-latest
          - example: CelestraCloud
            os: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Test ${{ matrix.example }}
        uses: brightdigit/swift-build@v1.5.0-beta.2
        id: build
        with:
          working-directory: Examples/${{ matrix.example }}
          type: ""

      - name: Process Coverage for ${{ matrix.example }}
        if: steps.build.outputs.contains-code-coverage == 'true'
        uses: sersoft-gmbh/swift-coverage-action@v4
        with:
          working-directory: Examples/${{ matrix.example }}
          fail-on-empty-output: true
        id: coverage-files

      - name: Upload Coverage to Codecov
        if: steps.build.outputs.contains-code-coverage == 'true'
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          flags: ${{ matrix.example }}-swift-${{ matrix.swift.version }}-${{ matrix.os }}
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ join(fromJSON(steps.coverage-files.outputs.files), ',') }}
