name: Swift Source Compatibility

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  swift-source-compat-suite:
    name: Test Swift ${{ matrix.container }} For Source Compatibility Suite
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    continue-on-error: ${{ contains(matrix.container, 'nightly') }}

    strategy:
      fail-fast: false
      matrix:
        container:
          - swift:6.1
          - swift:6.2
          - swiftlang/swift:nightly-6.3-noble

    container: ${{ matrix.container }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Swift 6.x For Source Compatibility
        run: swift build --disable-sandbox --verbose --configuration release -Xswiftc -swift-version -Xswiftc 6
